"""Tests for build/build_amber.py.

These tests run against the REAL build code with NO mocking of ``subprocess``.

They split into two groups:

* No-binary tests run in any environment (including CI without AmberTools).
  They cover the pure logic (force-field selection, box sizing, ion counts,
  directory cleanup) and the REAL input-file/command generation. For the latter
  the ``fake_amberhome`` fixture supplies stub ``tleap``/``cpptraj`` executables
  so the build code's real ``subprocess.run`` calls succeed and write their real
  input files, which the tests read back and assert on.

* Binary tests are gated behind ``skip_without_amber`` and actually run tleap to
  produce a topology/coordinate pair. They run where AmberTools is installed and
  skip cleanly otherwise.
"""

import os
import shutil
from pathlib import Path

import pytest

from molecular_simulations.build.build_amber import ExplicitSolvent, ImplicitSolvent

PDB_TEXT = 'ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00\n'


def _write_pdb(directory: Path, text: str = PDB_TEXT) -> Path:
    pdb = directory / 'test.pdb'
    pdb.write_text(text)
    return pdb


def _real_amberhome() -> str | None:
    """Resolve a real AMBERHOME for skip-gated binary tests."""
    home = os.environ.get('AMBERHOME')
    if home and (Path(home) / 'bin' / 'tleap').exists():
        return home
    tleap = shutil.which('tleap')
    if tleap is not None:
        return str(Path(tleap).resolve().parent.parent)
    return None


# ---------------------------------------------------------------------------
# ImplicitSolvent: construction + logic (no binary)
# ---------------------------------------------------------------------------


class TestImplicitSolvent:
    """Construction and force-field logic for ImplicitSolvent."""

    def test_init_with_path(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(path=tmp_path, pdb=str(pdb), protein=True)

        assert builder.path == tmp_path.resolve()
        assert 'leaprc.protein.ff19SB' in builder.ffs
        assert builder.tleap == str(tmp_path / 'bin' / 'tleap')

    def test_init_none_path_uses_pdb_dir(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(path=None, pdb=str(pdb), protein=True)

        assert builder.path == tmp_path.resolve()

    def test_no_amberhome_raises(self, tmp_path, monkeypatch):
        monkeypatch.delenv('AMBERHOME', raising=False)
        pdb = _write_pdb(tmp_path)
        with pytest.raises(ValueError, match='AMBERHOME is not set'):
            ImplicitSolvent(path=tmp_path, pdb=str(pdb), amberhome=None)

    def test_custom_output(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(path=tmp_path, pdb=str(pdb), out='custom_output.pdb')

        assert builder.out.name == 'custom_output.pdb'

    def test_forcefield_selection(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(
            path=tmp_path, pdb=str(pdb), protein=True, rna=True, dna=True
        )

        assert 'leaprc.protein.ff19SB' in builder.ffs
        assert 'leaprc.RNA.Shaw' in builder.ffs
        assert 'leaprc.DNA.OL21' in builder.ffs

    def test_kwargs_set_as_attributes(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(
            path=tmp_path, pdb=str(pdb), custom_param='custom_value', another_param=42
        )

        assert builder.custom_param == 'custom_value'
        assert builder.another_param == 42


# ---------------------------------------------------------------------------
# ImplicitSolvent: REAL tleap input generation (stub binary, no AmberTools)
# ---------------------------------------------------------------------------


class TestImplicitTleapInput:
    """The real tleap input file generated by tleap_it()."""

    def test_tleap_it_writes_real_input(self, tmp_path, fake_amberhome):
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(path=tmp_path, pdb=str(pdb), debug=True)

        # Runs the real tleap_it -> debug_tleap -> subprocess against the stub.
        builder.tleap_it()

        leap_file = tmp_path / 'tleap.in'
        assert leap_file.exists()
        content = leap_file.read_text()
        assert 'source leaprc.protein.ff19SB' in content
        assert f'loadpdb {builder.pdb}' in content
        assert 'set default pbradii mbondi3' in content
        assert f'savepdb prot {builder.out}' in content
        assert 'saveamberparm prot' in content
        assert 'quit' in content

        # The stub tleap was really invoked on that file (it copied it back).
        captured = (fake_amberhome / 'tleap_input.txt').read_text()
        assert captured == content

    def test_temp_tleap_runs_real_subprocess(self, tmp_path, fake_amberhome):
        """temp_tleap writes a temp input file and really invokes tleap on it."""
        pdb = _write_pdb(tmp_path)
        builder = ImplicitSolvent(path=tmp_path, pdb=str(pdb))

        builder.temp_tleap('source leaprc.protein.ff19SB\nquit\n')

        # The stub captured the exact input temp_tleap handed to tleap -f.
        captured = (fake_amberhome / 'tleap_input.txt').read_text()
        assert 'source leaprc.protein.ff19SB' in captured
        assert 'quit' in captured


# ---------------------------------------------------------------------------
# ExplicitSolvent: construction + logic (no binary)
# ---------------------------------------------------------------------------


class TestExplicitSolvent:
    """Construction and pure logic for ExplicitSolvent."""

    def test_init_defaults(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb), padding=15.0)

        assert builder.pad == 15.0
        assert 'leaprc.water.opc' in builder.ffs
        assert builder.water_box == 'OPCBOX'

    def test_polarizable(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb), polarizable=True)

        assert 'leaprc.protein.ff15ipq' in builder.ffs
        assert 'leaprc.water.spceb' in builder.ffs
        assert builder.water_box == 'SPCBOX'

    def test_disulfides(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        builder = ExplicitSolvent(
            path=tmp_path, pdb=str(pdb), disulfide_residues=[10, 20]
        )

        assert 'protein.10 = CYX' in builder.disulfides
        assert 'protein.20 = CYX' in builder.disulfides

    def test_get_ion_numbers(self):
        num_ions = ExplicitSolvent.get_ion_numbers(1_000_000)
        assert isinstance(num_ions, int)
        assert num_ions > 0

    def test_get_ion_numbers_scales_with_volume(self):
        small = ExplicitSolvent.get_ion_numbers(125_000)
        large = ExplicitSolvent.get_ion_numbers(1_000_000)
        assert large > small

    def test_get_pdb_extent(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb_text = (
            'ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00\n'
            'ATOM      2  CA  ALA A   1      10.000   5.000   3.000  1.00  0.00\n'
            'ATOM      3  C   ALA A   1       5.000  15.000   8.000  1.00  0.00\n'
        )
        pdb = _write_pdb(tmp_path, pdb_text)
        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb), padding=10.0)
        builder.pdb = str(pdb)

        # max extent is Y (15) + 2*10 padding = 35
        assert builder.get_pdb_extent() == 35

    def test_clean_up_directory(self, tmp_path, monkeypatch):
        monkeypatch.setenv('AMBERHOME', str(tmp_path))
        pdb = _write_pdb(tmp_path)
        (tmp_path / 'leap.log').write_text('log content')
        (tmp_path / 'protein.pdb').write_text('pdb content')
        (tmp_path / 'system.prmtop').write_text('topology')
        (tmp_path / 'system.inpcrd').write_text('coordinates')

        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb))
        builder.clean_up_directory()

        assert (tmp_path / 'build').exists()
        assert (tmp_path / 'system.prmtop').exists()
        assert (tmp_path / 'system.inpcrd').exists()
        # Intermediate files were moved into build/.
        assert (tmp_path / 'build' / 'leap.log').exists()
        assert (tmp_path / 'build' / 'protein.pdb').exists()


# ---------------------------------------------------------------------------
# ExplicitSolvent: REAL input generation (stub binary, no AmberTools)
# ---------------------------------------------------------------------------


class TestExplicitInputGeneration:
    """Real tleap/cpptraj inputs generated by ExplicitSolvent."""

    def test_assemble_system_writes_real_input(self, tmp_path, fake_amberhome):
        pdb = _write_pdb(tmp_path)
        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb), protein=True, debug=True)

        builder.assemble_system(dim=60.0, num_ions=15)

        content = (tmp_path / 'tleap.in').read_text()
        assert 'source leaprc.protein.ff19SB' in content
        assert 'source leaprc.water.opc' in content
        assert f'PROT = loadpdb {builder.pdb}' in content
        assert 'set PROT box {60.0 60.0 60.0}' in content
        assert 'solvatebox PROT OPCBOX {0 0 0}' in content
        assert 'addIonsRand PROT Na+ 15 Cl- 15' in content
        assert 'saveamberparm PROT' in content

    def test_prep_pdb_builds_real_cpptraj_input(self, tmp_path, fake_amberhome):
        pdb = _write_pdb(tmp_path)
        builder = ExplicitSolvent(path=tmp_path, pdb=str(pdb), protein=True)

        builder.prep_pdb()

        # The stub cpptraj captured the exact stdin the build code piped to it.
        cpptraj_input = (fake_amberhome / 'cpptraj_input.txt').read_text()
        assert f'parm {pdb}' in cpptraj_input
        assert f'loadcrd {pdb} name IN' in cpptraj_input
        assert 'prepareforleap' in cpptraj_input
        assert 'existingdisulfides' in cpptraj_input
        assert 'quit' in cpptraj_input

        # prep_pdb advances the working PDB and records the ss-bond leap file.
        assert builder.pdb.endswith('protein.pdb')
        assert builder.ss_bonds_leap == tmp_path / 'ss_bonds.leap'


# ---------------------------------------------------------------------------
# Skip-gated: real AmberTools execution
# ---------------------------------------------------------------------------


class TestRealAmberBuild:
    """End-to-end builds that actually run tleap (require AmberTools)."""

    def test_implicit_build_produces_topology(
        self, tmp_path, alanine_dipeptide_pdb, skip_without_amber
    ):
        home = _real_amberhome()
        builder = ImplicitSolvent(
            path=tmp_path,
            pdb=str(alanine_dipeptide_pdb),
            protein=True,
            glycans=False,
            amberhome=home,
        )
        builder.build()

        assert builder.out.with_suffix('.prmtop').exists()
        assert builder.out.with_suffix('.inpcrd').exists()

    def test_explicit_build_produces_topology(
        self, tmp_path, alanine_dipeptide_pdb, skip_without_amber
    ):
        home = _real_amberhome()
        builder = ExplicitSolvent(
            path=tmp_path,
            pdb=str(alanine_dipeptide_pdb),
            protein=True,
            padding=10.0,
            amberhome=home,
        )
        builder.build()

        assert builder.out.with_suffix('.prmtop').exists()
        assert builder.out.with_suffix('.inpcrd').exists()


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
